---
sudo: false
dist: bionic
language: python
python: 3.9
before_install: deactivate
notifications:
  email:
    if: branch = master
    recipients:
      - poppyschmo@protonmail.com

jobs:
  include:
    - name: tox
      install:
        - |
          ls -alh /opt/python
          versions=$(cd /opt/python; ls -1 | sort -Vr )
          versions=$(echo $versions)
          declare -p versions
          pyenv rehash
          pyenv shell $versions
        - python3.9 --version
        - python3.8 --version
        - python3.7 --version
        - python3.6 --version
        - python3.9 -mpip -V
        - pip install tox
      script: tox
    - &test-emacs
      name: emacs
      dist: trusty
      python: 3.6
      before_install:
        - deactivate
        - pyenv shell 3.6
      install:
        - git clone --depth=1 https://github.com/rejeep/evm.git $HOME/.evm
        - export PATH="$HOME/.evm/bin:$PATH"
        - evm config path /tmp
        - evm install $EVM_EMACS --use --skip
      env: EVM_EMACS=emacs-26.1-travis
      script: emacs --version && cd emacs && make
    - <<: *test-emacs
      env: EVM_EMACS=emacs-25.1-travis
    - <<: *test-emacs
      python: 3.5
      before_install:
        - deactivate
        - pyenv shell 3.5
      env:
        - EVM_EMACS=emacs-25.1-travis
        - EMACS_PY35=1
    - name: vim8
      install:
        - pyenv shell 3.9
        - sudo add-apt-repository -y ppa:jonathonf/vim
        - sudo apt-get update -q
        - sudo apt-get install -y vim
        - vim --version | grep -q york
      script: cd vim && make vim8
    - name: neovim
      install:
        - pyenv shell 3.9
        - |
          export TRAVIS_BUILD_DIR=/opt
          url=https://raw.githubusercontent.com/neovim/bot-ci
          url+=/master/scripts/travis-setup.sh
          eval "$(curl -Ss $url) nightly-x64"
        - nvim --version
      script: cd vim && make neovim
