---
sudo: false
dist: xenial
language: python
python: 3.8
before_install: deactivate
notifications:
  email:
    if: branch = master
    recipients:
      - poppyschmo@protonmail.com

jobs:
  include:
    - name: tox
      python: 3.5
      install:
        - |
          archive_url=https://storage.googleapis.com/travis-ci-language-archives
          archive_url+=/python/binaries/ubuntu/16.04/x86_64/python-3.8.tar.bz2
          curl -sSf --retry 5 -o python-3.8.tar.bz2 $archive_url
          sudo tar xjf python-3.8.tar.bz2 --directory /
          sudo chown -R travis:travis /opt/python
          ls -alh /opt/python
          versions=$(cd /opt/python; ls -1 | sort -Vr )
          versions=$(echo $versions)
          declare -p versions
          pyenv rehash
          pyenv shell $versions
        - python3.8 --version
        - python3.7 --version
        - python3.6 --version
        - python3.5 --version
        - python3.5 -mpip -V
        - pip install tox
      script: tox
    - &test-emacs
      name: emacs
      dist: trusty
      python: 3.6
      before_install:
        - deactivate
        - pyenv shell 3.6
      install:
        - git clone --depth=1 https://github.com/rejeep/evm.git $HOME/.evm
        - export PATH="$HOME/.evm/bin:$PATH"
        - evm config path /tmp
        - evm install $EVM_EMACS --use --skip
      env: EVM_EMACS=emacs-26.1-travis
      script: emacs --version && cd emacs && make
    - <<: *test-emacs
      env: EVM_EMACS=emacs-25.1-travis
    - <<: *test-emacs
      python: 3.5
      before_install:
        - deactivate
        - pyenv shell 3.5
      env:
        - EVM_EMACS=emacs-25.1-travis
        - EMACS_PY35=1
    - name: vim8
      install:
        - pyenv shell 3.8
        - sudo add-apt-repository -y ppa:jonathonf/vim
        - sudo apt-get update -q
        - sudo apt-get install -y vim
        - vim --version | grep -q york
      script: cd vim && make vim8
    - name: neovim
      install:
        - pyenv shell 3.8
        - |
          export TRAVIS_BUILD_DIR=/opt
          url=https://raw.githubusercontent.com/neovim/bot-ci
          url+=/master/scripts/travis-setup.sh
          eval "$(curl -Ss $url) nightly-x64"
        - nvim --version
      script: cd vim && make neovim
    - stage: deploy
      name: PyPI
      before_install: skip
      script: skip
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        skip_upload_docs: true
        user: poppyschmo
        password:
          secure: "gz/YHqvK9MPb9rI5fcUR1igwb2XlAIcQhPxtGLcf2PXHtCq1aVXjBH7uWtOyxwpp2j2EboLepY18u31ZS0AbXqLHzjH/omcDqAmLlMm4Aqd1lHpXu/s908PaxjCH6/ph1f8vSQ5J4J5K/g3kkqSNJgjY54VzLZk4DZBGloMQyAfGjOHd5Zbj89959qCvxtJqpG1+Vk50qMynjJn/ViidMZ3CpJ/nt4YjX9hMY1EwR2b4jUyJk/6V4iLOVJha1QD9nL2X56aC+QOUpUuc+gIlPA5k0WZX1XgVydz/waW+3uHEqsUcAiIEiYT7Z08XclV3iO0g68jUYdbCb+ZFwQqXhFXRd3/fG39S9GMBWoChUl8qn72WPvdQ1TRug6YJqF3qzOksChjqd4BKDvh20twLDwAfIXJmDK5Szqiaijz7PJOyaBBKUA8KFyyz27Yuo92P5mSQP9/QRPFteISZbI/FXWrAQOlrCrmAehumPxxtPZueLgAzi6SkXrXSzHur2IRhf5Z4ORQQdYbrkjPV9bfvCgCQvQUvU37WzeW2cnw2k1fsi2m/pTO8UFmAOgFiVWjO+NWtUc0ML7guoP/WoElW06BmexSqkte1xH7Klu/CI0PIuFV5kGtEnRkeFsHqp236o5cJSnLwlflmSBhK7AXVSK5O2+rv2LtzbF/D5L3TUCw="
        on:
          repo: poppyschmo/pytest-pdb-break
          tags: true

