---
sudo: false
language: python
before_install: deactivate

jobs:
  include:
    - name: tox
      dist: xenial
      python: 3.7
      install:
        - pyenv shell 3.6 3.7
        - pip install tox
      script: tox
    - &test-emacs
      name: emacs
      dist: trusty
      python: 3.6
      install:
        - pyenv shell 3.6
        - git clone --depth=10 https://github.com/rejeep/evm.git $HOME/.evm
        - export PATH="$HOME/.evm/bin:$PATH"
        - evm config path /tmp
        - evm install $EVM_EMACS --use --skip
      env: EVM_EMACS=emacs-26.1-travis
      script: emacs --version && cd emacs && make
    - <<: *test-emacs
      env: EVM_EMACS=emacs-25.1-travis
