---
sudo: false
language: python
before_install: deactivate

jobs:
  include:
    - name: tox
      dist: xenial
      python: 3.7
      install:
        - |
          if ! test -e /opt/python3.6; then
            three_six=$(ls -1 /opt/python | grep 3.6 | sort -Vr | head -n1)
            cd /opt/python && ln -s "$three_six" 3.6 && cd -
          fi
        - pyenv shell 3.7 3.6
        - pip install tox
      script: tox
    - &test-emacs
      name: emacs
      dist: trusty
      python: 3.6
      install:
        - pyenv shell 3.6
        - git clone --depth=10 https://github.com/rejeep/evm.git $HOME/.evm
        - export PATH="$HOME/.evm/bin:$PATH"
        - evm config path /tmp
        - evm install $EVM_EMACS --use --skip
      env: EVM_EMACS=emacs-26.1-travis
      script: emacs --version && cd emacs && make
    - <<: *test-emacs
      env: EVM_EMACS=emacs-25.1-travis
    - name: vim8
      dist: trusty
      python: 3.6
      install:
        - pyenv shell 3.6
        - sudo add-apt-repository -y ppa:jonathonf/vim
        - sudo apt-get update -q
        - sudo apt-get install -y vim
        - vim --version | grep -q york
      script: cd vim && make vim8
    - name: neovim
      dist: trusty
      python: 3.6
      install:
        - pyenv shell 3.6
        - |
          export TRAVIS_BUILD_DIR=/opt
          url=https://raw.githubusercontent.com/neovim/bot-ci
          url+=/master/scripts/travis-setup.sh
          eval "$(curl -Ss $url) nightly-x64"
        - nvim --version
      script: cd vim && make neovim
